const productsData = [
    {
        id: 1,
        name: "Teclado Redragon Kumara K552",
        category: "teclados",
        cardImg: "./products/kumara.webp",
        price: 24999,
    },
    {
        id: 2,
        name: "Teclado Logitech Prodigy",
        category: "teclados" ,
        category: "todos" ,
        cardImg: "./products/tecladologitech.webp",
        price: 23499,
    },
    {
        id: 3,
        name: "Teclado T-Dagger Bora",
        category: "teclados",
        cardImg: "./products/tecladotdagger.webp",
        price: 15000,
    },
    {
        id: 4,
        name: "Mouse Logitech G Pro Hero",
        category: "mouse",
        cardImg: "./products/mouselogitech.webp",
        price: 20299,
    },
    {
        id: 5,
        name: "Mouse Redragon Centrophorus2",
        category: "mouse",
        cardImg: "./products/mouseredragon.webp",
        price: 7099,
    },
    {
        id: 6,
        name: "Mouse HyperX Pulsefire Pro",
        category: "mouse",
        cardImg: "./products/mousehx.webp",
        price: 27300,
    },
    {
        id: 7,
        name: "Auriculares Logitech G Series",
        category:"auriculares" ,
        cardImg:"./products/auriculareslogitech.webp" ,
        price: 36000,
    },
    {
        id: 8,
        name:"Auriculares Redragon Zeus" ,
        category:"auriculares" ,
        cardImg: "./products/auricularesredragon.webp",
        price: 29999,
    },
    {
        id: 9,
        name: "Auriculares HyperX Cloud Stinger",
        category:"auriculares" ,
        cardImg: "./products/auriculareshx.webp",
        price: 23999,
    },
    {
        id: 10,
        name: "Monitor Samsung 24 75hz",
        category: "monitores",
        cardImg: "./products/monitor75hz.webp",
        price: 59000,
    },
    {
        id: 11,
        name:"Monitor 24 Samsung 144hz" ,
        category: "monitores",
        cardImg:"./products/monitor144hz.webp" ,
        price: 93500,
    },
    {
        id: 12,
        name: "Monitor Philips Led 24 60hz",
        category: "monitores",
        cardImg: "./products/monitorphilips.webp",
        price: 51000,
    },
    {
        id: 13,
        name: "Kit Microfono Soporte Brazo",
        category: "microfonos",
        cardImg: "./products/microfonobm800.webp",
        price: 15000,
    },
    {
        id: 14,
        name: "Micrófono Redragon BLAZAR",
        category:"microfonos" ,
        cardImg: "./products/microfonoredragon.webp",
        price: 29999,
    },
    {
        id: 15,
        name: "Micrófono Shure MV7X",
        category: "microfonos",
        cardImg: "./products/microfonoshure.webp",
        price: 124000,
    },
    {
        id: 16,
        name: "Webcam Camara Web 1080p Noga",
        category:"webcams" ,
        cardImg: "./products/webcamnoga.webp",
        price: 4500,
    },
    {
        id: 17,
        name: "Cámara web Logitech C920 30FPS",
        category: "webcams",
        cardImg: "./products/webcamlogitech.webp",
        price: 29999,
    },
    {
        id: 18,
        name:"Cámara web Redragon Fobos 30FPS " ,
        category:"webcams" ,
        cardImg: "./products/webcamredragon.webp",
        price: 13999,
    },
    
];

const appState ={
    activeFilter: null,
};